apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: static-route-operator
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: static-route-operator
  template:
    metadata:
      labels:
        name: static-route-operator
    spec:
      serviceAccountName: static-route-operator
      hostNetwork: true
      tolerations:
      - operator: Exists
      imagePullSecrets:
      - name: {{ .Values.registry_secret }}
      containers:
      - name: static-route-operator
        image: {{ .Values.registry }}/{{ .Values.image }}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: OPERATOR_NAME
          value: "static-route-operator"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
