apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: static-route-operator
spec:
  selector:
    matchLabels:
      name: static-route-operator
  template:
    metadata:
      labels:
        name: static-route-operator
    spec:
      serviceAccountName: static-route-operator
      hostNetwork: true
      tolerations:
      - operator: Exists
      imagePullSecrets:
      - name: core.harbor.10.100.52.147.nip.io-staticroutes-operator
      containers:
      - name: static-route-operator
        image: core.harbor.10.100.52.147.nip.io/staticroutes-operator/staticroutes-operator:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
          runAsGroup: 2000
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: OPERATOR_NAME
          value: "static-route-operator"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
